website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, make_response
from flask_login import login_required, current_user
from website.models import Food, Log
from .extensions import db
from sqlalchemy.exc import IntegrityError  
from datetime import datetime
from weasyprint import HTML
import os

views = Blueprint('views', __name__)

@views.route('/')
def landing():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    
    return render_template("land.html")

@views.route('/home')
@login_required
def home():
    logs = Log.query.filter_by(user_id=current_user.id).order_by(Log.date.desc()).all()

    log_dates = []
        
    for log in logs:
        proteins = 0
        carbs = 0
        fat = 0
        calories = 0
        
        for food in log.foods:
            proteins += food.proteins
            carbs += food.carbs
            fat += food.fats
            calories += food.calories
            
        log_dates.append({
            'log': log,
            'log_date': log.date,
            'proteins': proteins,
            'carbs': carbs,
            'fat': fat,
            'calories': calories
        })

    return render_template("home.html", log_dates=log_dates, user=current_user)


@views.route('/create_log', methods=['POST'])
@login_required
def create_log():
    date = request.form.get('date')

    # Check if the date is empty
    if not date:
        flash('Please select a date!', 'error')
        return redirect(url_for('views.add_date'))  # Redirect back to the form

    try:
        # Attempt to parse the date
        log = Log(date=datetime.strptime(date, '%Y-%m-%d'), user_id=current_user.id)
        db.session.add(log)
        db.session.commit()
        flash('Log created successfully!', 'success')
        return redirect(url_for('views.view', log_id=log.id))
    except ValueError:
        # Catch any parsing errors and inform the user
        flash('Invalid date format. Please select a valid date.', 'error')
        return redirect(url_for('views.add_date'))

@views.route('/add')
@login_required
def add():
    foods = Food.query.filter_by(user_id=current_user.id).all()
    return render_template("add.html", foods=foods, food=None)

@views.route('/add', methods=['POST'])
@login_required
def add_post():
    food_id = request.form.get('food-id')
    food_name = request.form.get('food-name')
    proteins = request.form.get('protein')
    carbs = request.form.get('carbohydrates')
    fats = request.form.get('fat')

    if food_id:
        # Editing an existing food
        food = Food.query.get_or_404(food_id)
        if food.user_id != current_user.id:
            flash("You don't have permission to edit this food item.", 'danger')
            return redirect(url_for('views.add'))

        food.name = food_name
        food.proteins = proteins
        food.carbs = carbs
        food.fats = fats
    else:
        # Adding a new food
        existing_food = Food.query.filter_by(name=food_name, user_id=current_user.id).first()
        if existing_food:
            flash('You have already added this food item!', 'warning')
            return redirect(url_for('views.add'))

        new_food = Food(
            name=food_name,
            proteins=proteins,
            carbs=carbs,
            fats=fats,
            user_id=current_user.id  # Save the current user's ID
        )
        db.session.add(new_food)

    try:
        db.session.commit()
        flash('Food item added & updated successfully!', 'success')
    except IntegrityError:
        db.session.rollback()
        flash('An error occurred while saving the food item.', 'danger')

    return redirect(url_for('views.add'))

@views.route('/delete_food/<int:food_id>')
def delete_food(food_id):
    food = Food.query.get_or_404(food_id)
    if food:
        db.session.delete(food)
        db.session.commit()
        flash('Food item deleted successfully!', 'success')
    else:
        flash('Food item not found.', 'warning')
    return redirect(url_for('views.add'))

@views.route('/edit_food/<int:food_id>')
@login_required
def edit_food(food_id):
    food = Food.query.filter_by(id=food_id, user_id=current_user.id).first_or_404()
    
    # Fetch only the foods added by the current user
    foods = Food.query.filter_by(user_id=current_user.id).all()
    return render_template('add.html', food=food, foods=foods)

@views.route('/view/<int:log_id>')
@login_required
def view(log_id):
    # Fetching the log and filtering the food added by the currect user
    log = Log.query.filter_by(id=log_id, user_id=current_user.id).first_or_404()
    foods = Food.query.filter_by(user_id=current_user.id).all()

    # Calculating the totals for proteins, carbs, fats, and calories
    totals = {
        'proteins' : 0,
        'carbs' : 0,
        'fat' : 0,
        'calories' : 0
    }

    # Update totals based on the foods in the log
    for food in log.foods:
        totals['proteins'] += food.proteins
        totals['carbs'] += food.carbs
        totals['fat']  += food.fats
        totals['calories'] += food.calories

    # Render the view template with only the current user's foods
    return render_template("view.html", foods=foods, log=log, totals=totals)

@views.route('/add_food_to_log/<int:log_id>', methods=['POST'])
@login_required
def add_food_to_log(log_id):
    log = Log.query.get_or_404(log_id)
    selected_food = request.form.get('food-select')
    food = Food.query.get(int(selected_food))
    if food and log:
        log.foods.append(food)
        db.session.commit()
    return redirect(url_for('views.view', log_id=log_id))

    return redirect(url_for('views.view', log_id=log_id))

@views.route('/remove_food_from_log/<int:log_id>/<int:food_id>')
def remove_food_from_log(log_id, food_id):
    log = Log.query.get(log_id)
    food = Food.query.get(food_id)
    log.foods.remove(food)
    db.session.commit()
    return redirect(url_for('views.view', log_id=log_id))

@views.route('/download_summary')
@login_required
def download_summary():
    # Fetch all logs for the current user
    logs = Log.query.filter_by(user_id=current_user.id).order_by(Log.date.desc()).all()

    # Prepare a summary of nutrients for the month
    log_summaries = []
    total_proteins = total_carbs = total_fat = total_calories = 0

    for log in logs:
        log_proteins = log_carbs = log_fat = log_calories = 0

        for food in log.foods:
            log_proteins += food.proteins
            log_carbs += food.carbs
            log_fat += food.fats
            log_calories += food.calories

        log_summaries.append({
            'date': log.date.strftime('%B %d, %Y'),
            'proteins': log_proteins,
            'carbs': log_carbs,
            'fat': log_fat,
            'calories': log_calories,
        })

        total_proteins += log_proteins
        total_carbs += log_carbs
        total_fat += log_fat
        total_calories += log_calories

    # Render the PDF-friendly HTML template
    html = render_template('monthly_summary_pdf.html', logs=log_summaries, 
                           total_proteins=total_proteins, total_carbs=total_carbs, 
                           total_fat=total_fat, total_calories=total_calories)

    # Convert the HTML to PDF
    pdf = HTML(string=html).write_pdf()

    # Generate a downloadable response
    response = make_response(pdf)
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = 'attachment; filename=monthly_summary.pdf'

    return response

website/templates/add.html
{% extends "base.html" %}

{% block title %}Add Food Item{% endblock %}

{% block content %}
<div class="container-fluid" id="wrapper">
    <div class="row" id="homeJumbo">
        <div class="overlay"></div>
        <div class="col-lg-12">
            <h1>
                <a href="#">FOOD TRACKER</a>
            </h1>
            
            <div class="row t20">
                <div class="col-lg-4 col-lg-offset-4">
                    <ul class="nav nav-pills nav-justified">
                        <li role="presentation" class="active">
                            <a href="{{ url_for('views.home') }}" title="Home">Home</a>
                        </li>
                        <li role="presentation" class="ml-auto active" >
                            <a href="{{ url_for('views.add') }}" title="Add Food Item" class="no-wrap">Add Food Item</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row t20">
        <div class="col-lg-8 col-lg-offset-2">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3 class="lean-h text-black">
                        <i class="glyphicon glyphicon-plus-sign"></i> New Food Form
                    </h3>
                    <hr />
                    <form action="{{ url_for('views.add') }}" method="POST" role="form">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="food-name">Food Name</label>
                                    <input type="text" class="form-control" id="food-name" name="food-name" placeholder="Food Name" value="{{ food.name }}" autofocus>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="protein">Protein</label>
                                    <input type="number" class="form-control" id="protein" name="protein" placeholder="Protein" value="{{ food.proteins }}">
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="carbohydrates">Carbohydrates</label>
                                    <input type="number" class="form-control" id="carbohydrates" name="carbohydrates" placeholder="Carbohydrates" value="{{ food.carbs }}">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="fat">Fat</label>
                                    <input type="number" class="form-control" id="fat" name="fat"placeholder="Fat" value="{{ food.fats }}">
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label style="visibility:hidden">submit</label>
                                    <input type="hidden" name="food-id" value="{{ food.id }}">  
                                    <button type="submit" class="btn btn-primary btn-block">
                                        <i class="glyphicon glyphicon-upload"></i> Submit
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form> 
                </div>
            </div>
        </div>
    </div>

    <div class="row t20">
        <div class="col-lg-8 col-lg-offset-2">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h4 class="lean-h text-black">
                        <i class="glyphicon glyphicon-th-list"></i> Existing Food Items
                    </h4>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-hover table-bordered">
                        <thead>
                            <tr>
                                <th style="width: 5%;">#</th>
                                <th>Name</th>
                                <th style="width: 10%;">Protein</th>
                                <th style="width: 16%;">Carbohydrates</th>
                                <th style="width: 10%;">Fat</th>
                                <th style="width: 12%;">Calories</th>
                                <th style="width: 12%;">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for food in foods %}
                            <tr>
                                <td>{{ food.id }}</td>
                                <td>{{ food.name }}</td>
                                <td>{{ food.proteins }}</td>
                                <td>{{ food.carbs }}</td>
                                <td>{{ food.fats }}</td>
                                <td>{{ food.calories }}</td>
                                <td>
                                    <a href="{{ url_for('views.edit_food', food_id=food.id) }}" class="btn btn-default btn-xs">
                                        <i class="glyphicon glyphicon-pencil"></i> Edit
                                    </a>
                                    <a href="{{ url_for('views.delete_food', food_id=food.id) }}" class="btn btn-danger btn-xs">
                                        <i class="glyphicon glyphicon-trash"></i> Delete
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

<footer>
    <div class="row pad">
        <div class="col-lg-12 text-center">
            Copyright &copy; 2024 <strong>Food Tracker</strong>
        </div>
    </div>
</footer>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bs/css/united.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button 
          class="navbar-toggler" 
          type="button" 
          data-toggle="collapse" 
          data-target="#navbar"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" id="home" href="/">Home</a>
              <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
              {% else %}
              <a class="nav-item nav-link" id="login" href="/login">Login</a>
              <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
              {% endif %}
            </div>
        </div>
    </nav>

    <!-- Existing flash messages block -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    <!-- New flash messages block -->
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <ul class="flashes">
          {% for category, message in messages %}
            <li class="alert alert-{{ category }}">{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>

    <script
    type="text/javascript"
    src="{{ url_for('static', filename='index.js')}}">

    </script>
    <script src="{{ url_for('static', filename='bs/js/jquery.min.js') }}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{ url_for('static', filename='bs/js/bootstrap.min.js') }}"></script>
</body>
</html>

website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container-fluid" id="wrapper">

    <div class="row" id="homeJumbo">
        <div class="overlay"></div>
        <div class="col-lg-12">
            <h1>
                <a href="#">FOOD TRACKER</a>
            </h1>
            
            <div class="row t20">
                <div class="col-lg-4 col-lg-offset-4">
                    <ul class="nav nav-pills nav-justified">
                        <li role="presentation" class="active">
                            <a href="{{ url_for('views.home') }}" title="Home">Home</a>
                        </li>
                        <li role="presentation" class="ml-auto active" >
                            <a href="{{ url_for('views.add') }}" title="Add Food Item" class="no-wrap">Add Food Item</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row t20">
        <div class="col-lg-4 col-lg-offset-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="{{ url_for('views.create_log') }}" method="POST" role="form" id="date-form">
                        <div class="form-group">
                            <label><i class="glyphicon glyphicon-plus-sign"></i> Add New Date</label>
                            <div class="input-group">
                                <input type="date" class="form-control" name="date" id="date-input" placeholder="Select New Date" aria-label="date" aria-describedby="add-btn">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-primary" id="add-btn">
                                        <i class="glyphicon glyphicon-plus-sign"></i> Add Date
                                    </button>

                                </span>
                            </div>
                        </div>
                    </form>                    
                </div>
            </div>
        </div>
    </div>
    <div class="row t20">
        <div class="col-lg-5 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-7 col-sm-offset-2 text-center h-100">
            <div class="col-lg-12">
                <h4 class="text-left text-black"><strong>Monthly Summary</strong></h4>
            </div>
            <div class="button-container">
                <div class="button">
                    <div class="content">
                        <i class="bx bx-cloud-download"></i>
                        <span class="button-text text-white">
                            <a href="{{ url_for('views.download_summary') }}">Download</a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div></br>
    

    <div class="row t20">
        <div class="col-lg-12">
            <h4 class="text-center text-black"><strong>Existing Records ({{log_dates|length}})</strong></h4>
        </div>
    </div>

    {% if log_dates|length == 0 %}
<div class="row t20">
    <div class="col-lg-12">
        <p class="text-center text-muted">No logs found. Start by adding a new food log!</p>
    </div>
</div>
{% else %}
    {% for row in log_dates|batch(4) %}
    <div class="row t20">
        {% for log_date in row %}
        <div class="col-lg-3">
            <div class="panel panel-warning">
                <div class="panel-body text-bold">
                    <i class="glyphicon glyphicon-calendar"></i> {{ log_date['log_date'].strftime('%B %d, %Y') }}
                    <a class="btn btn-primary btn-xs pull-right" href="{{ url_for('views.view', log_id=log_date['log'].id) }}">
                        View <i class="glyphicon glyphicon-arrow-right"></i>
                    </a>
                </div>
                <ul class="list-group">
                    <li class="list-group-item text-bold"><span class="badge">{{ log_date['proteins'] }}</span> Protein</li>
                    <li class="list-group-item text-bold"><span class="badge">{{ log_date['carbs'] }}</span> Carbohydrate</li>
                    <li class="list-group-item text-bold"><span class="badge">{{ log_date['fat'] }}</span> Fat</li>
                    <li class="list-group-item text-bold"><span class="badge">{{ log_date['calories'] }}</span> Calories</li>
                </ul>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
{% endif %}

</div>

<footer>
    <div class="row pad">
        <div class="col-lg-12 text-center">
            Copyright &copy; 2024 <strong>Food Tracker</strong>
        </div>
    </div>
</footer>
{% endblock %}

website/templates/land.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <!-- Hero Section -->
    <section class="hero">
        <div class="hero-content">
            <h1>Track Your Nutrition with <span>Food Tracker</span></h1>
            <p>Your personal food journal to manage and monitor what you eat.</p>
            <a id="signUp" href="/sign-up" class="cta-btn">Get Started</a>
        </div>
    </section>

    <!-- Features Section -->
    <section class="features">
        <h2>Features</h2>
        <div class="features-list">
            <div class="feature-item">
                <h3>Easy Logging</h3>
                <p>Quickly log your meals and track your daily intake with ease.</p>
            </div>
            <div class="feature-item">
                <h3>Nutrition Tracking</h3>
                <p>Stay on top of your protein, fat, carb, and calorie consumption.</p>
            </div>
            <div class="feature-item">
                <h3>Personalized Insights</h3>
                <p>Receive personalized recommendations based on your eating habits.</p>
            </div>
        </div>
    </section>

    <!-- How It Works Section -->
    <section class="how-it-works">
        <h2>How It Works</h2>
        <div class="steps">
            <div class="step">
                <h3>1. Sign Up</h3>
                <p>Create your account to start tracking.</p>
            </div>
            <div class="step">
                <h3>2. Add Food</h3>
                <p>Log your meals and snacks every day.</p>
            </div>
            <div class="step">
                <h3>3. Monitor Progress</h3>
                <p>Check your nutritional progress and adjust your diet.</p>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer>
        <p>&copy; 2024 Food Tracker. All rights reserved.</p>
        <a id="signUp" href="/login">Login</a> | <a id="signUp" href="/sign-up">Sign Up</a>
    </footer>
{% endblock %}

website/templates/view.html
{% extends "base.html" %}

{% block title %}Food Tracker | View Details{% endblock %}

{% block content %}
<div class="container-fluid" id="wrapper">

    <div class="row" id="homeJumbo">
        <div class="overlay"></div>
        <div class="col-lg-12">
            <h1>
                <a href="#">FOOD TRACKER</a>
            </h1>
            
            <div class="row t20">
                <div class="col-lg-4 col-lg-offset-4">
                    <ul class="nav nav-pills nav-justified">
                        <li role="presentation" class="active">
                            <a href="{{ url_for('views.home') }}" title="Home">Home</a>
                        </li>
                        <li role="presentation" class="ml-auto active" >
                            <a href="{{ url_for('views.add') }}" title="Add Food Item" class="no-wrap">Add Food Item</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row t20">
        <div class="col-lg-4 col-lg-offset-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="{{ url_for('views.add_food_to_log', log_id=log.id) }}" method="POST" role="form">
                        <div class="form-group">
                            <label>Add Food</label>
                            <div class="input-group">
                                <select class="form-control" name="food-select">
                                    {% for food in foods %}
                                    <option value="{{ food.id }}">{{ food.name }}</option>
                                    {% endfor %}
                                    
                                </select>
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-primary" id="add-btn">
                                        <i class="glyphicon glyphicon-plus-sign"></i> Add Food
                                    </button>
                                </span>
                            </div>
                        </div>
                    </form> 
                </div>
            </div>
        </div>
    </div>

    <div class="row t20">
        <div class="col-lg-8 col-lg-offset-2">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3 class="lean-h text-black">
                        <i class="glyphicon glyphicon-calendar"></i> {{ log.date.strftime('%B %d, %Y') }}
                    </h3>

                    <div class="row">
                        <div class="col-lg-3">
                            <h4 class="lean-h" style="font-size: 14px;">
                                Protein: &nbsp;<strong class="f25" style="font-size: 14px;">{{ totals['proteins'] }}</strong>
                            </h4>
                        </div>
                        <div class="col-lg-3">
                            <h4 class="lean-h" style="font-size: 14px;">
                                Carbohydrates: <strong class="f25" style="font-size: 14px;">{{ totals['carbs'] }}</strong>
                            </h4>
                        </div>
                        <div class="col-lg-3">
                            <h4 class="lean-h" style="font-size: 14px;">
                                Fat: <strong class="f25" style="font-size: 14px;">{{ totals['fat'] }}</strong>
                            </h4>
                        </div>
                        <div class="col-lg-3">
                            <h4 class="lean-h" style="font-size: 14px;">
                                Calories: <strong class="f25" style="font-size: 14px;">{{ totals['calories'] }}</strong>
                            </h4>
                        </div>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-striped table-hover table-bordered">
                        <thead>
                            <tr>
                                <th style="width: 5%;">#</th>
                                <th>Name</th>
                                <th style="width: 10%;">Protein</th>
                                <th style="width: 16%;">Carbohydrates</th>
                                <th style="width: 10%;">Fat</th>
                                <th style="width: 12%;">Calories</th>
                                <th style="width: 12%;">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for food in log.foods %}
                            <tr>    
                                <td>{{ loop.index }}</td>
                                <td>{{ food.name }}</td>
                                <td>{{ food.proteins }}</td>
                                <td>{{ food.carbs }}</td>
                                <td>{{ food.fats }}</td>
                                <td>{{ food.calories }}</td>
                                <td> 
                                    <a href="{{ url_for('views.remove_food_from_log', log_id=log.id, food_id=food.id)}}" class="btn btn-danger btn-xs">
                                        <i class="glyphicon glyphicon-trash"></i> Delete
                                    </a>
                                </td>  
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

<footer>
    <div class="row pad">
        <div class="col-lg-12 text-center">
            Copyright &copy; 2024 <strong>Food Tracker</strong>
        </div>
    </div>
</footer>
{% endblock %}